### ISSUE TITLE
How to put folders in the configuration folder of the wildfly?

### ISSUE THREAD

**Issue by jean-merelis** [openshift-cartridges/openshift-wildfly-cartridge#33]
I tried to put a folder directly in "/.openshift/config/" but did not work.

I need add a folder in "<wildfly>/standalone/configuration/"

**Comment by jean-merelis** [comment]
I used "rhc ssh". This works for me.

        $ rhc ssh
        $ cp -avr ~/app-root/repo/.openshift/config/themes ~/wildfly/standalone/configuration

**Comment by fjuma** [comment]
Great. By default, only files from .openshift/config will be copied to the server's standalone/configuration directory so the "rhc ssh" approach you mentioned is currently the way to go for getting folders copied over.
