### ISSUE TITLE
Install of cartridge fails in Openshift 2.2 Enterprise due to missing manifest.yml

### ISSUE THREAD

**Issue by vinnielima** [openshift-cartridges/openshift-wildfly-cartridge#34]
Performing git clone on OSE 2.2 node:

git clone git://github.com/openshift-cartridges/openshift-wildfly-cartridge.git

Then Installing fails as it cannot find manifest in sub directories:

oo-admin-cartridge --action install --recursive --source /usr/libexec/openshift/cartridges/openshift-wildfly-cartridge

Requires manually creating subdirectories and copying manifest to the location OSE is looking for:

mkdir bin/metadata
mkdir versions/metadata
mkdir env/metadata
mkdir hooks/metadata
mkdir metadata/metadata
cp metadata/manifest.yml versions/metadata
cp metadata/manifest.yml env/metadata
cp metadata/manifest.yml hooks/metadata
cp metadata/manifest.yml metadata/metadata
cp metadata/manifest.yml bin/metadata

Then the installation succeeds:

oo-admin-cartridge --action install --recursive --source /usr/libexec/openshift/cartridges/openshift-wildfly-cartridge
succeeded

oo-admin-cartridge -l
(redhat, mongodb, 2.4, 0.2.13.1)
(redhat, ruby, 1.8, 0.0.21)
(redhat, ruby, 1.9, 0.0.21)
(redhat, ruby, 2.0, 0.0.21)
(redhat, jbossews, 1.0, 0.0.25.1)
(redhat, jbossews, 2.0, 0.0.25.1)
(redhat, cron, 1.4, 0.0.13)
(redhat, jenkins-client, 1, 0.0.12)
(redhat, python, 2.6, 0.0.22)
(redhat, python, 2.7, 0.0.22)
(redhat, python, 3.3, 0.0.22)
(redhat, nodejs, 0.10, 0.0.22.1)
(redhat, mysql, 5.1, 0.2.19.1)
(redhat, mysql, 5.5, 0.2.19.1)
(redhat, diy, 0.1, 0.0.13)
(redhat, haproxy, 1.4, 0.0.22.1)
(redhat, perl, 5.10, 0.0.18)
(redhat, php, 5.3, 0.0.22)
(redhat, php, 5.4, 0.0.22)
(redhat, jenkins, 1, 0.0.18.1)
(redhat, postgresql, 8.4, 0.3.19)
(redhat, postgresql, 9.2, 0.3.19)
(jboss, wildfly, 8, 0.0.6)

**Comment by fjuma** [comment]
See [Section 5.1.1, Importing, Activating, and Deactivating Cartridges](https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Administration_Guide/chap-Cartridge_Management.html#Importing_Activating_and_Deactivating_Cartridges) in the OpenShift Enterprise Administration Guide for instructions on managing downloadable cartridges. The downloadable cartridge manifest can be imported on the broker using the following command:

oo-admin-ctl-cartridge -c import --url URL_to_Cartridge_Manifest --activate

**Comment by vinnielima** [comment]
While this command may be accurate for internet-connected brokers, this option does not work on isolated environments. Most OSE deployments are not internet connected, or with limited internet connectivity.

Therefore, the procedure originally posted (installing the cartridge on each node, then activating it within the broker) is still valid in my opinion.

**Comment by fjuma** [comment]
Since this isn't specific to the WildFly cartridge (i.e., the manifest issue should occur with other downloadable cartridges as well), feel free to create an OpenShift bugzilla issue.

Thanks!
