### ISSUE TITLE
Cartridge build fails expecting a different version of apache-maven

### ISSUE THREAD

**Issue by vinnielima** [openshift-cartridges/openshift-wildfly-cartridge#38]
This Wildfly cartridge builds fine on OpenShift Enterprise 2.2, but I’m running into errors when pushing changes either via Eclipse or initiating a build directly with Jenkins:
 
[repo] $ /bin/sh -xe /tmp/hudson156385329508737646.sh
+ alias 'rsync=rsync --delete-after -azO -e '\''/usr/libexec/openshift/cartridges/jenkins/bin/git_ssh_wrapper.sh'\'''
+ upstream_ssh=moeiz-wildfly-1@wildfly-moeiz.domain.com
+ rsync --delete-after -azO -e /usr/libexec/openshift/cartridges/jenkins/bin/git_ssh_wrapper.sh 'moeiz-wildfly-1@wildfly-moeiz.domain.com:~/.m2/' /var/lib/openshift/moeiz-wildflybldr-1//.m2/
Warning: Permanently added 'wildfly-moeiz.domain.com,<IP>' (RSA) to the list of known hosts.
+ gear build
Building git ref 'origin/HEAD', commit 68e5bca
Found pom.xml... attempting to build with 'mvn -e clean package -Popenshift -DskipTests'
/var/lib/openshift/moeiz-wildflybldr-1/wildfly//bin/tools/mvn: line 6: /usr/share/java/apache-maven-3.0.4/bin/mvn: No such file or directory
/var/lib/openshift/moeiz-wildflybldr-1/wildfly//bin/tools/mvn: line 6: exec: /usr/share/java/apache-maven-3.0.4/bin/mvn: cannot execute: No such file or directory
An error occurred executing 'gear build' (exit code: 126)
Error message: CLIENT_ERROR: Failed to execute: 'control build' for /var/lib/openshift/moeiz-wildflybldr-1/wildfly
 
For more details about the problem, try running the command again with the '--trace' option.
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
 
I believe maven within the wildfly gear is trying to communicate with a specific version of maven within Openshift (version 3.0.4).

Upon further investigation, OpenShift OSE 2.2 is bundled with Maven 3.0.3.  Is this a configurable item in this cartridge, to be able to specify the version to be used (in this case, Maven?).

If not, can it be as an enhancement?

Thanks.

**Comment by fjuma** [comment]
I'll look into this. Would it be possible for you to let me know the output of executing the following command after ssh'ing into one of your cartridge instances on OSE 2.2:

``stat /etc/alternatives/maven-3.0``

Thanks!

**Comment by vinnielima** [comment]
# stat /etc/alternatives/maven-3.0/
  File: `/etc/alternatives/maven-3.0/'
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 695374      Links: 6
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-03-10 14:48:52.034249905 -0400
Modify: 2015-02-06 17:48:53.434000023 -0500
Change: 2015-02-06 17:48:53.434000023 -0500

**Comment by fjuma** [comment]
Thanks! One last question - what's the value of $M2_HOME?

**Comment by vinnielima** [comment]
empty

# echo $M2_HOME

**Comment by fjuma** [comment]
The WildFly cartridge currently uses a custom mvn script (in $OPENSHIFT_WILDFLY_DIR/bin/tools/mvn) to provide a way to override the hard-coded JAVA_HOME variable in the /usr/bin/mvn script (for [BZ-1109980](https://bugzilla.redhat.com/show_bug.cgi?id=1109980)). As a quick fix, you could ssh into your instance and update the value of $M2_HOME in $OPENSHIFT_WILDFLY_DIR/bin/tools/mvn.

**Comment by Moeiz** [comment]
Hi fjuma,
Changing the value of $M2_HOME in $OPENSHIFT_WILDFLY_DIR/bin/tools/mvn to /usr/share/java/apache-maven-3.0.3 and restarting the cartridge still results in the same build error:

/var/lib/openshift/moeiz-wildflybldr-1/wildfly//bin/tools/mvn: line 6: /usr/share/java/apache-maven-3.0.4/bin/mvn: No such file or directory
/var/lib/openshift/moeiz-wildflybldr-1/wildfly//bin/tools/mvn: line 6: exec: /usr/share/java/apache-maven-3.0.4/bin/mvn: cannot execute: No such file or directory

**Comment by fjuma** [comment]
It doesn't look like $M2_HOME was successfully changed. In general, these steps should work:

1) ``rhc ssh <APP>`` and then update the value of $M2_HOME in ``wildfly/bin/tools/mvn``
2)`` rhc git-clone <APP>`` (if you haven't already cloned your repo locally)
3) ``cd <APP>`` (local git repo)
4) make a change to the local repo
5) ``git push`` (the new value of $M2_HOME should appear in the output)

**Comment by Moeiz** [comment]
So, once I stopped being stubborn and closely followed your instructions, the new build was successful.

The problem starts once you integrate a Jenkins Builder to handle code changes. The bldr slave reverts back to using 3.0.4 for maven, so I'm not sure if Jenkins is pulling the code for the bldr from this git directly or from the base cartridge in OpenShift

**Comment by fjuma** [comment]
You could add a "pre_build" action hook to the app's git repo that updates the value of $M2_HOME, e.g., create an .openshift/action_hooks/pre_build file that contains the following:

```
#!/bin/sh
sed -i 's/M2_HOME=.*/M2_HOME=\/usr\/share\/java\/apache-maven-3.0.3/' $OPENSHIFT_WILDFLY_DIR/bin/tools/mvn
```

Then, make this file executable and commit it to your app's git repo:

``chmod +x .openshift/action_hooks/pre_build``

This should ensure the correct M2_HOME location gets used.
