### ISSUE TITLE
Which precondition needs to be available on the node

### ISSUE THREAD

**Issue by planonsoftware** [openshift-cartridges/openshift-wildfly-cartridge#41]
We have installed openshift origin internally , when i try to install this cartridge i got the following error:

Error: Failed to execute: 'control start' for /var/lib/openshift/551bed89740240aa43000061/wildfly
Starting wildfly cart wildfly process failed to start
WildFly 8 administrator added. Please make note of these credentials: Username: adminygj21GS Password: K5E9_ALDfm-T run 'rhc port-forward jbosswildfly' to access the web admin area on port 9990.
Unable to complete the requested operation due to: An invalid exit code (157) was returned from the server node-dev-eu-m-atd-00.infra.planoncloud.com. This indicates an unexpected problem during the execution of your request.. Reference ID: ba41925d1c1260ab66c3da2a45adf366

What do i need to install on the node, it is centos.

**Comment by fjuma** [comment]
Since the WildFly cartridge defaults to using JDK 8, you'll need to either install it or replace the java8 marker file in the application's git repository with a java7 marker file.

**Comment by planonsoftware** [comment]
JDK 8 is installed on the node, but do i not need to install Wildfly on the node, or is it part of the cartridge

**Comment by fjuma** [comment]
The WildFly binaries are provided by the cartridge so you don't need to install it.

Just to clarify, the creation process is failing for you, right? i.e., you're not able to ssh into your instance and take a look at the log file, correct?

**Comment by fjuma** [comment]
To get more information on why it's failing to start, you could temporarily try using the following fork of the cartridge that modifies the cartridge's start script to always exit with a return code of 0. This should allow app creation to always succeed so that you can then ssh into your app and take a look at the server log file to see what the actual error is:

```
rhc app create debugwildfly https://raw.githubusercontent.com/fjuma/openshift-wildfly-cartridge/debug/metadata/manifest.yml
```

**Comment by planonsoftware** [comment]
ik got the following message : /var/lib/openshift/551e8407740240df9000002b/wildfly/bin/control: line 303: //exit: No such file or directory

**Comment by fjuma** [comment]
Sorry about that, there was a minor typo in the fork. Please try again with the same command:

```
rhc app create debugwildfly https://raw.githubusercontent.com/fjuma/openshift-wildfly-cartridge/debug/metadata/manifest.yml
```

**Comment by planonsoftware** [comment]
Hi,

We found the issue it is java version related. Thanks.

Met vriendelijke groet / Yours sincerely / Mit freundlichen Grüßen / Très cordialement,

Henk Laracker
Lead architect / Planon cloud center manager
Development
____________________________

Planon B.V.
Wijchenseweg 8
6537 TL Nijmegen
P.O. Box 38074
6503 AB Nijmegen
The Netherlands
T: +31 (0) 6 1209 7794
F: +31 (0) 24 642 2942

Email:    Henk.Laracker@planonsoftware.com<mailto:Henk.Laracker@planonsoftware.com>
Linkedin:http://nl.linkedin.com/in/hlaracker
Twitter: https://twitter.com/HenkLaracker
Web:  http://www.planonsoftware.com<http://www.planonsoftware.com/>
Skype:   henk.laracker


Deze email en alle bijlagen zijn slechts voor gebruik door de beoogde ontvanger. De email kan intellectueel eigendom en/of vertrouwelijke informatie bevatten. Het mag niet worden gekopieerd, openbaar gemaakt, bewaard of gebruikt worden door anderen dan waarvoor deze bestemd is. Bent u niet de beoogde ontvanger,verwijdert u dan deze email met alle bijlagen en kopieën onmiddellijk en informeer de afzender.
This e-mail and any attachment is for authorised use by the intended recipient(s) only. It may contain proprietary material, confidential information and/or be subject to legal privilege. It should not be copied, disclosed to, retained or used by, any other party. If you are not an intended recipient then please promptly delete this e-mail and any attachment and all copies and inform the sender.
