### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by lombamarc** [openshift-cartridges/openshift-wildfly-cartridge#46]
Hi,

I installed with rhc wildfly app (http://3dapp-thinkalize.rhcloud.com/) but web console not works (http://3dapp-thinkalize.rhcloud.com/console).

How can i access to web console of wildfly?

**Comment by fjuma** [comment]
Due to port restrictions on OpenShift, port forwarding is needed to access WildFly's web console. See https://github.com/openshift-cartridges/openshift-wildfly-cartridge#super-secret-hint-dont-tell-anyone for details on how to do this.

**Comment by lombamarc** [comment]
I run "rhc port-forward" on my prompt (local pc)  or in ssh connection
(openshift server) ?

Thanks

2015-05-22 19:49 GMT+02:00 Farah Juma <notifications@github.com>:

> Due to port restrictions on OpenShift, port forwarding is needed to access
> WildFly's web console. See
> https://github.com/openshift-cartridges/openshift-wildfly-cartridge#super-secret-hint-dont-tell-anyone
> for details on how to do this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/46#issuecomment-104726719>
> .
>



-- 
Lombardo Marco

**Comment by fjuma** [comment]
It should be run on your local machine. Remember to include the app name in the command as well, e.g., "rhc port-forward WILDFLY_APP_NAME".

**Comment by lombamarc** [comment]
Not works. Below the messages of the prompt:

C:\...>rhc port-forward 3dapp
DL is deprecated, please use Fiddle
Checking available ports ... Could not parse PKey: no start line
Usage: rhc port-forward <application>
Pass '--help' to see the full list of options



2015-05-22 20:07 GMT+02:00 Farah Juma <notifications@github.com>:

> It should be run on your local machine. Remember to include the app name
> in the command as well, e.g., "rhc port-forward WILDFLY_APP_NAME".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/46#issuecomment-104732707>
> .
>



-- 
Lombardo Marco

**Comment by fjuma** [comment]
http://stackoverflow.com/questions/28682443/openshift-port-forwarding

**Comment by lombamarc** [comment]
Yes, solved :D

2015-05-22 22:25 GMT+02:00 Farah Juma <notifications@github.com>:

> http://stackoverflow.com/questions/28682443/openshift-port-forwarding
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/46#issuecomment-104759523>
> .
>



-- 
Lombardo Marco
