### ISSUE TITLE
Problems when deploy EAR

### ISSUE THREAD

**Issue by lombamarc** [openshift-cartridges/openshift-wildfly-cartridge#47]
Hi, 
i use port-forwarding to activate web console.
I try do load more times an EAR in deployment section of web console but the screen processes data without giving any result for hours.  server.log not show errors.
Instead, In my local wildfly installation same ear works correctly.
EAR has 22MB of dimension.

Are there any limitation of this cartridge for ear deployment?

**Comment by lombamarc** [comment]
Hi, i deploy ear with jboss-cli e deploy prompt (--disabled) but start of ear does no work.
Following error:
HASE__ is missing [jboss.naming.context.java.compass-remote]"]}
2015-05-24 16:58:46,697 ERROR [org.jboss.as.server] (XNIO-1 task-10) JBAS015870: Deploy of deployment "compass2.ear" was rolled back with the following failure message: {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.persistenceunit.\"compass2.ear#projectDatabase\".__FIRST_PHASE__ is missing [jboss.naming.context.java.compass-remote]"]}

datasource are configured and in a local pc the ear works.

Any ideas?

**Comment by fjuma** [comment]
Some information about deploying EAR files on OpenShift can be found here: https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges

Looks like your datasource is missing or not enabled. You can configure your datasource using the standalone.xml file in your app's git repository (i.e., <APP>/.openshift/config/standalone.xml). Note that the WildFly cartridge's standalone.xml file comes with some pre-configured datasources, one for MySQL and one for PostgreSQL (see https://developers.openshift.com/en/wildfly-ds.html and https://developers.openshift.com/en/managing-adding-a-database.html). It also contains an example h2 datasource.

For additional questions on this, please visit https://help.openshift.com/. Thanks!

**Comment by lombamarc** [comment]
Thank you for the support.

My datasource is h2 type.

*1) My standalone.xml (datasource section):*
 <datasource jta="true" jndi-name="java:/compass-remote"
pool-name="Compass" enabled="true" use-ccm="true">
                    <connection-url>jdbc:h2:mem:compass</connection-url>
                    <driver-class>org.h2.Driver</driver-class>
                    <driver>h2</driver>
                    <pool>
                        <min-pool-size>0</min-pool-size>
                        <initial-pool-size>0</initial-pool-size>
                        <max-pool-size>0</max-pool-size>
                        <allow-multiple-users>false</allow-multiple-users>
                    </pool>
                    <security>
                        <user-name>sa</user-name>
                        <password>sa</password>
                    </security>
                    <validation>
                        <validate-on-match>false</validate-on-match>
                        <background-validation>false</background-validation>
                        <use-fast-fail>false</use-fast-fail>
                    </validation>
                    <timeout>
                        <set-tx-query-timeout>false</set-tx-query-timeout>
                        <blocking-timeout-millis>0</blocking-timeout-millis>
                        <idle-timeout-minutes>0</idle-timeout-minutes>
                        <query-timeout>0</query-timeout>
                        <use-try-lock>0</use-try-lock>
                        <allocation-retry>0</allocation-retry>

<allocation-retry-wait-millis>0</allocation-retry-wait-millis>
                    </timeout>
                    <statement>

<share-prepared-statements>false</share-prepared-statements>
                    </statement>
                </datasource>



*2) Error after rhc deploy:*
2015-05-24 16:58:46,255 INFO  [org.jboss.as.jpa] (MSC service thread 1-4)
JBAS011401: Read persistence.xml for projectDatabase
2015-05-24 16:58:46,696 ERROR
[org.jboss.as.controller.management-operation] (XNIO-1 task-10) JBAS014613:
Operation ("deploy") failed - address: ([("deployment" => "compass2.ear")])
- failure description: {"JBAS014771: Services with missing/unavailable
dependencies" =>
["jboss.persistenceunit.\"compass2.ear#projectDatabase\".__FIRST_PHASE__ is
missing [jboss.naming.context.java.compass-remote]"]}
2015-05-24 16:58:46,697 ERROR [org.jboss.as.server] (XNIO-1 task-10)
JBAS015870: Deploy of deployment "compass2.ear" was rolled back with the
following failure message: {"JBAS014771: Services with missing/unavailable
dependencies" =>
["jboss.persistenceunit.\"compass2.ear#projectDatabase\".__FIRST_PHASE__ is
missing [jboss.naming.context.java.compass-remote]"]}



I apprecciate if you give a support.

KR
Marco

2015-05-25 16:16 GMT+02:00 Farah Juma <notifications@github.com>:

> Some information about deploying EAR files on OpenShift can be found here:
> https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges
>
> Looks like your datasource is missing or not enabled. You can configure
> your datasource using the standalone.xml file in your app's git repository
> (i.e., /.openshift/config/standalone.xml). Note that the WildFly
> cartridge's standalone.xml file comes with some pre-configured datasources,
> one for MySQL and one for PostgreSQL (see
> https://developers.openshift.com/en/wildfly-ds.html and
> https://developers.openshift.com/en/managing-adding-a-database.html). It
> also contains an example h2 datasource.
>
> For additional questions on this, please visit https://help.openshift.com/.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/47#issuecomment-105241579>
> .
>



-- 
Lombardo Marco

**Comment by fjuma** [comment]
Perhaps the answer here might help:

https://developer.jboss.org/thread/241289

**Comment by lombamarc** [comment]
Works but during deploying in server.log i obtain a lot of "Out Of Memory".

In this moment all operation java like are blocked.

For example if i put on command line "java -version" i obtain:
Error occurred during initialization of VM
java.lang.OutOfMemoryError: unable to create new native thread.

Is there a way to clean threads?


2015-05-27 0:15 GMT+02:00 Farah Juma <notifications@github.com>:

> Perhaps the answer here might help:
>
> https://developer.jboss.org/thread/241289
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/47#issuecomment-105685132>
> .
>



-- 
Lombardo Marco

**Comment by lombamarc** [comment]
Hi, i solved with a restart of server and redeploy.

My last question:

in local mode (127.0.0.1) my webapp works and respond correctly on
http://127.0.0.1:8082/<<context-root>> with rhc port-forward on.

What is the correct internet url for openshift app to reach the web
application (server side)?

I try http://<<full openshift app url>>:8080/<<context-root>>  or http://<<full
openshift app url>>/<<context-root>> but not work.

Thanks

Marco

2015-05-31 22:49 GMT+02:00 Marco Lombardo <ing.lombardo.marco@gmail.com>:

> Works but during deploying in server.log i obtain a lot of "Out Of Memory".
>
> In this moment all operation java like are blocked.
>
> For example if i put on command line "java -version" i obtain:
> Error occurred during initialization of VM
> java.lang.OutOfMemoryError: unable to create new native thread.
>
> Is there a way to clean threads?
>
>
> 2015-05-27 0:15 GMT+02:00 Farah Juma <notifications@github.com>:
>
>> Perhaps the answer here might help:
>>
>> https://developer.jboss.org/thread/241289
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/47#issuecomment-105685132>
>> .
>>
>
>
>
> --
> Lombardo Marco
>
>



-- 
Lombardo Marco

**Comment by fjuma** [comment]
As mentioned in https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges:

>The WAR files that you add into the deployments directory will be deployed at a context that matches the name of the WAR file.
For Example:
If you add a file called mywebsite.war, it will be available at app-domain.rhcloud.com/mywebsite. If there is an application that you would like to be available at app-domain.rhcloud.com/ (also known as the root context) then you should name that file ROOT.war.

>A note about EAR files. An EAR file can contain WAR files, JAR files, EJB's and other archives. If you add multiple WAR files inside of your EAR file, they will each be deployed at their individual context. Any libraries added as JAR files should be made available to all applications that are deployed inside of your EAR file, but not any other EAR files that have been deployed.

**Comment by lombamarc** [comment]
There is only an ear file in my wildly cartridge.

Is very strange what happen.

Recap:

http://3dapp-thinkalize.rhcloud.com/compass-webapp ==> not work (!!!)

If i activate "rhc port-forward 3dapp" on my pc,
http://127.0.0.1:8082/compass-webapp ==> work

If it helps, below the output of rhc port forward :

haproxy 127.0.0.1:8080  =>  127.12.6.2:8080
haproxy 127.0.0.1:8081  =>  127.12.6.3:8080
java    127.0.0.1:3528  =>  127.12.6.1:3528
java    127.0.0.1:7600  =>  127.12.6.1:7600
java    127.0.0.1:8082  =>  127.12.6.1:8080
java    127.0.0.1:9990  =>  127.12.6.1:9990

Then, which  is the correct url path on 3dapp-thinkalize.rhcloud.com to
reach my context root "compas-webapp"?


2015-06-01 22:30 GMT+02:00 Farah Juma <notifications@github.com>:

> As mentioned in
> https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges
> :
>
> The WAR files that you add into the deployments directory will be deployed
> at a context that matches the name of the WAR file.
> For Example:
> If you add a file called mywebsite.war, it will be available at
> app-domain.rhcloud.com/mywebsite. If there is an application that you
> would like to be available at app-domain.rhcloud.com/ (also known as the
> root context) then you should name that file ROOT.war.
>
> A note about EAR files. An EAR file can contain WAR files, JAR files,
> EJB's and other archives. If you add multiple WAR files inside of your EAR
> file, they will each be deployed at their individual context. Any libraries
> added as JAR files should be made available to all applications that are
> deployed inside of your EAR file, but not any other EAR files that have
> been deployed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/47#issuecomment-107697716>
> .
>



-- 
Lombardo Marco

**Comment by lombamarc** [comment]
Hi,

is it perhaps a problem of widlfy cartrige binding?

Follow this link ==>
https://developers.openshift.com/en/managing-port-binding-routing.html

2015-06-02 0:42 GMT+02:00 Marco Lombardo <ing.lombardo.marco@gmail.com>:

> There is only an ear file in my wildly cartridge.
>
> Is very strange what happen.
>
> Recap:
>
> http://3dapp-thinkalize.rhcloud.com/compass-webapp ==> not work (!!!)
>
> If i activate "rhc port-forward 3dapp" on my pc,
> http://127.0.0.1:8082/compass-webapp ==> work
>
> If it helps, below the output of rhc port forward :
>
> haproxy 127.0.0.1:8080  =>  127.12.6.2:8080
> haproxy 127.0.0.1:8081  =>  127.12.6.3:8080
> java    127.0.0.1:3528  =>  127.12.6.1:3528
> java    127.0.0.1:7600  =>  127.12.6.1:7600
> java    127.0.0.1:8082  =>  127.12.6.1:8080
> java    127.0.0.1:9990  =>  127.12.6.1:9990
>
> Then, which  is the correct url path on 3dapp-thinkalize.rhcloud.com to
> reach my context root "compas-webapp"?
>
>
> 2015-06-01 22:30 GMT+02:00 Farah Juma <notifications@github.com>:
>
>> As mentioned in
>> https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges
>> :
>>
>> The WAR files that you add into the deployments directory will be
>> deployed at a context that matches the name of the WAR file.
>> For Example:
>> If you add a file called mywebsite.war, it will be available at
>> app-domain.rhcloud.com/mywebsite. If there is an application that you
>> would like to be available at app-domain.rhcloud.com/ (also known as the
>> root context) then you should name that file ROOT.war.
>>
>> A note about EAR files. An EAR file can contain WAR files, JAR files,
>> EJB's and other archives. If you add multiple WAR files inside of your EAR
>> file, they will each be deployed at their individual context. Any libraries
>> added as JAR files should be made available to all applications that are
>> deployed inside of your EAR file, but not any other EAR files that have
>> been deployed.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift-cartridges/openshift-wildfly-cartridge/issues/47#issuecomment-107697716>
>> .
>>
>
>
>
> --
> Lombardo Marco
>
>



-- 
Lombardo Marco
