### ISSUE TITLE
Troubles with pom.xml file

### ISSUE THREAD

**Issue by zipzit** [openshift-cartridges/openshift-wildfly-cartridge#69]
I'm looking at the openshift-wildfly-cartridge/versions/8/template/pom.xml file. ref:`https://github.com/openshift-cartridges/openshift-wildfly-cartridge/blob/master/versions/8/template/pom.xml` In fact, I see that exact file generated into my gear at Openshift when I choose the cartridge: "WildFly Application Server 8.2.1.Final" , which I have downloaded via git clone. (thank you for integrating that!)

I'm re-learning java, using maven. (Haven't touched java since Netbeans years ago.)  For this exercise, I'm using code from (github) javee7-samples, and in particular the websocket chat example.  I've removed the chatTest.java files so testing in not interfering via dependencies.  I do NOT have a WEB-INF web.xml file in the project.  I'm using atom.io as my simple editor, and the command line to use maven.  (I'm actually using git bash cli tool in Windows.)

    $ mvn -v
    Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
    Maven home: c:\Program Files\Apache\apache-maven-3.3.3-bin
    Java version: 1.8.0_65, vendor: Oracle Corporation
    Java home: c:\Program Files\Java\jdk1.8.0_65\jre
    Default locale: en_US, platform encoding: Cp1252
    OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

Unfortunately with this pom.xml file there is no way to successfully create a .war package via $ mvn   I can compile classes fine. (via `$ mvn -f pom.xml compile`)  No go on generating the .war files. (via `$ mvn -f pom.xml package`)  The error I'm seeing is: 

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war)
    on project wildflychatserver: Error assembling WAR: webxml attribute is required 
    (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]

For what ever reason, the lines of code  `<failOnMissingWebXml>false</failOnMissingWebXml>` is not working like I expected.

Is this an opportunity for improvement within the cartridge pom.xml file?  Or, ooops, something I'm doing wrong?  Am I doing this correctly?

Update: I digging thru the git clone download from openshift, and wow, I don't even see a single .war file in there.  So the easy way to fix my issue is to implement via clone modifications.  I still think there is something amiss in the pom.xml file though.  Info posted here in case others hit the same bump in the road, if that's okay.  

Again, many thanks to the authors for their work on this project...

**Comment by fjuma** [comment]
The ```failOnMissingWebXml``` property is part of the "openshift" profile in the [pom.xml](https://github.com/openshift-cartridges/openshift-wildfly-cartridge/blob/master/versions/8/template/pom.xml#L32) file (this is the profile that gets invoked when OpenShift builds your app for you). If you'd like to use this profile locally, it can be specified using the -P option, e.g.,

```mvn package -Popenshift```

**Comment by zipzit** [comment]
fjuma, you rock.  `$ mvn -f pom.xml package -Popenshift` totally nailed it.  And as you've guessed I'm a  maven rookie. Many thanks for your help here.
