### ISSUE TITLE
How does clustering work with this cartridge?

### ISSUE THREAD

**Issue by mrj365** [openshift-cartridges/openshift-wildfly-cartridge#74]
I see the following properties in the manifest.yml file, but I'm not sure how I can utilize this for clustering. Are you able to provide any more information on this or point me to a doc?

Private-Port-Name: CLUSTER_PORT
Private-Port: 7600
Public-Port-Name: CLUSTER_PROXY_PORT

**Comment by fjuma** [comment]
The following two links should help you get started:

https://developers.openshift.com/managing-your-applications/scaling.html
https://blog.openshift.com/how-to-host-your-java-ee-application-with-auto-scaling/
